name: calendar_application
description: A simple interactive calendar app with Firebase integration for event management.
# This package is not intended for publication to pub.dev as it is for personal or internal use.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  google_sign_in: ^6.2.1
  firebase_analytics: ^10.8.5

  # State Management
  provider: ^6.1.1

  # UI Components
  table_calendar: ^3.0.9
  flutter_svg: ^2.0.9

  # Utilities
  intl: ^0.19.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  # Enables the use of Material Design widgets and themes in the app.
  uses-material-design: true