// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKDYp0OtZez-wiLSIV-lWcKEJlXUkIRnc',
    appId: '1:424625358311:web:62b41c3e5392c42da1e942',
    messagingSenderId: '424625358311',
    projectId: 'myproject-a8b30',
    authDomain: 'myproject-a8b30.firebaseapp.com',
    storageBucket: 'myproject-a8b30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyl1bG8GGS4n728IpcfNwTb1xbEZ2lmMQ',
    appId: '1:424625358311:android:fbfcd503175e13e0a1e942',
    messagingSenderId: '424625358311',
    projectId: 'myproject-a8b30',
    storageBucket: 'myproject-a8b30.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKDYp0OtZez-wiLSIV-lWcKEJlXUkIRnc',
    appId: '1:424625358311:web:5a4377e61b1b5394a1e942',
    messagingSenderId: '424625358311',
    projectId: 'myproject-a8b30',
    authDomain: 'myproject-a8b30.firebaseapp.com',
    storageBucket: 'myproject-a8b30.firebasestorage.app',
  );
}
